import type { BodyConfig, HttpRequestSpec, KeyValue } from '../model/types.js';

/**
 * Helpers for the in-app AI features (natural language → request, generated tp tests). Model output
 * is untrusted text: these functions only extract data from it, and the results are shown to the user
 * (and labelled as AI-generated) before anything runs.
 */

import { extractCodeBlock } from '@testpion/shared';
export { extractCodeBlock };

const METHODS = new Set(['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS']);

/**
 * Parse a request the model described as JSON:
 * `{ "method", "url", "headers": [{ "key", "value" }] | { name: value }, "body": string | object | null, "name"? }`.
 * Throws when there is no usable JSON with a URL.
 */
export function parseGeneratedRequest(text: string): { name?: string; request: HttpRequestSpec } {
  const raw = extractCodeBlock(text, ['json']);
  const start = raw.indexOf('{');
  const end = raw.lastIndexOf('}');
  if (start < 0 || end <= start) throw new Error('The model did not return a JSON request');
  let d: Record<string, unknown>;
  try {
    d = JSON.parse(raw.slice(start, end + 1)) as Record<string, unknown>;
  } catch (e) {
    throw new Error(`The model returned invalid JSON: ${(e as Error).message}`);
  }
  const url = typeof d.url === 'string' ? d.url.trim() : '';
  if (!url) throw new Error('The model did not return a URL');
  const method = String(d.method ?? 'GET').toUpperCase();
  const headersIn = d.headers;
  const headers: KeyValue[] = Array.isArray(headersIn)
    ? headersIn.filter((h): h is { key: string; value?: unknown } => !!h && typeof h === 'object' && typeof (h as { key?: unknown }).key === 'string').map((h) => ({ key: h.key, value: String(h.value ?? '') }))
    : headersIn && typeof headersIn === 'object'
      ? Object.entries(headersIn as Record<string, unknown>).map(([key, value]) => ({ key, value: String(value ?? '') }))
      : [];
  let body: BodyConfig | undefined;
  if (d.body !== undefined && d.body !== null && d.body !== '') {
    const content = typeof d.body === 'string' ? d.body : JSON.stringify(d.body, null, 2);
    const isJson = typeof d.body === 'object' || /^\s*[{[]/.test(content);
    body = { type: isJson ? 'json' : 'text', content };
    if (isJson && !headers.some((h) => h.key.toLowerCase() === 'content-type')) headers.push({ key: 'Content-Type', value: 'application/json' });
  }
  return {
    name: typeof d.name === 'string' && d.name.trim() ? d.name.trim().slice(0, 80) : undefined,
    request: { method: METHODS.has(method) ? method : 'GET', url, headers, ...(body ? { body } : {}) },
  };
}

/** Clean model output into a tp test script, with a header saying it was AI-generated. */
export function generatedTestScript(text: string, model: string): string {
  const code = extractCodeBlock(text, ['javascript', 'js'])
    .split(/\r?\n/)
    // the sandbox only provides crypto-js and uuid: drop other imports so the script can run
    .filter((l) => !/^\s*import\s/.test(l) && !/\brequire\(\s*['"](?!crypto-js['"]|uuid['"])[^'"]*['"]\s*\)/.test(l))
    .join('\n')
    .trim();
  if (!/\b(pm|tp)\.test\s*\(/.test(code)) throw new Error('The model did not return any tp.test(...) calls');
  return `// Tests generated by AI (${model}). Review them before relying on them.\n${code}\n`;
}
