import { describe, expect, it } from 'vitest';
import { extractCodeBlock, generatedTestScript, parseGeneratedRequest } from '../../packages/core/src/index.js';

describe('AI assist helpers', () => {
  it('extracts fenced code, preferring the wanted language', () => {
    expect(extractCodeBlock('Here:\n```yaml\na: 1\n```\n```json\n{"a":1}\n```', ['json'])).toBe('{"a":1}');
    expect(extractCodeBlock('```\nplain\n```')).toBe('plain');
    expect(extractCodeBlock('  no fences  ')).toBe('no fences');
  });

  it('parses a generated request with header list or map and a JSON body', () => {
    const r = parseGeneratedRequest('Sure!\n```json\n{"name":"Create patient","method":"post","url":"{{baseUrl}}/patients","headers":{"Authorization":"Bearer {{accessToken}}"},"body":{"name":"Biscuit","species":"dog"}}\n```');
    expect(r.name).toBe('Create patient');
    expect(r.request).toEqual({
      method: 'POST',
      url: '{{baseUrl}}/patients',
      headers: [
        { key: 'Authorization', value: 'Bearer {{accessToken}}' },
        { key: 'Content-Type', value: 'application/json' },
      ],
      body: { type: 'json', content: '{\n  "name": "Biscuit",\n  "species": "dog"\n}' },
    });
    const g = parseGeneratedRequest('{"method":"FETCH","url":"https://x.io/a","headers":[{"key":"Accept","value":"text/plain"}],"body":null}');
    expect(g.request).toEqual({ method: 'GET', url: 'https://x.io/a', headers: [{ key: 'Accept', value: 'text/plain' }] });
  });

  it('rejects output without a usable request', () => {
    expect(() => parseGeneratedRequest('I cannot help with that.')).toThrow(/JSON/);
    expect(() => parseGeneratedRequest('{"method":"GET"}')).toThrow(/URL/);
    expect(() => parseGeneratedRequest('{"url": }')).toThrow(/invalid JSON/);
  });

  it('turns generated tests into a labelled script and drops imports', () => {
    const s = generatedTestScript('```javascript\nconst x = require("fs");\npm.test("ok", () => pm.response.to.have.status(200));\n```', 'mock/mock-gpt');
    expect(s).toBe('// Tests generated by AI (mock/mock-gpt). Review them before relying on them.\npm.test("ok", () => pm.response.to.have.status(200));\n');
    expect(generatedTestScript('const CryptoJS = require("crypto-js");\npm.test("a", () => {});', 'm')).toContain('require("crypto-js")');
    expect(() => generatedTestScript('console.log(1)', 'm')).toThrow(/tp\.test/);
  });
});
